[package]
name = "lvgl-sys"
description = "Raw bindings to the LVGL C library."
version = "0.6.2"
authors = ["Rafael Caricio <crates.lvgl-sys@caric.io>", "Nia Espera <a5b6@riseup.net>"]
edition = "2021"
license = "MIT"
homepage = "https://github.com/rafaelcaricio/lvgl-rs"
repository = "https://github.com/rafaelcaricio/lvgl-rs"
readme = "README.md"
categories = ["external-ffi-bindings", "embedded", "gui", "no-std"]
keywords = ["littlevgl", "lvgl"]
build = "build.rs"
links = "lvgl"
exclude = [
    "vendor/lvgl/demos",
    "vendor/lvgl/tests",
    "vendor/lvgl/examples",
    "vendor/lvgl/docs",
    "vendor/lvgl/scripts",
    "vendor/lvgl/env_support",
]

[lib]
name = "lvgl_sys"

[dependencies]
cty = "0.2.2"

[build-dependencies]
cc = "1.0.79"
bindgen = "0.65.1"

[features]
use-vendored-config = []
drivers = []
rust_timer = []
# if LV_TICK_CUSTOM = 1, then lv_tick_inc function is unavailable
custom_timer = []
